name: Mise à jour Scores

on:
  schedule:
    - cron: '*/10 * * * *'  # S'exécute toutes les 10 minutes automatiquement
  workflow_dispatch:        # Garde aussi le lancement manuel pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Lancement du script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python get_live.py
